container:
  image: debian:stable-backports
  privileged: true

build_linux_task:
  name: Build on Linux

  install_dependencies_script:
    - apt-get update
    - apt-get install -y
        qt6-base-dev
        qt6-multimedia-dev
        qt6-wayland-dev
        qt6-tools-dev
        libasound2-dev
        libfluidsynth-dev
        build-essential
        libapparmor-dev
        libcap-dev
        libqt63dcore6
        libqt6core6t64
        wget file

  build_script:
    - qmake6
    - make -j$(nproc)

  appimage_script:
    - ./scripts/build-appimage.sh

  binary_artifacts:
    path: midieditor

  upload_artifacts:
    path: MidiEditor-Linux-x86_64.AppImage
